import { Project } from "@/types/projects.types";

export const PROJECT_STATUSES = {
  DRAFT: "Draft",
  SUBMITTED_TO_AEE: "Submitted to AEE",
  REJECTED_BY_AEE: "Rejected by AEE",
  SUBMITTED_TO_CE: "Submitted to CE",
  REJECTED_BY_CE: "Rejected by CE",
  SUBMITTED_TO_MD: "Submitted to MD",
  REJECTED_BY_MD: "Rejected by MD",
  SUBMITTED_TO_EXECUTING_DEPARTMENT: "Submitted to Executing Department",
  REJECTED_BY_EXECUTING_DEPARTMENT: "Rejected by Executing Department",
  APPROVED: "Approved",
  ONGOING: "Ongoing",
  PENDING: "Pending",
  COMPLETED: "Completed",
};

export const MOCK_PROJECT: Project = {
  id: "PROJ_1754574223988",
  name: "Engineering College Construction for Dhemaji",
  description:
    "This is a construction project of Engineering College, Dhemaji. This is a Central Government project.",
  status: "Submitted to AEE",
  progress: 0,
  budget: 20000000,
  budgetUtilized: 0,
  createdBy: "Ratan",
  createdByName: "Education Department",
  createdAt: "2025-08-10",
  updatedAt: "2025-08-07",
  startDate: "2025-08-15",
  expectedCompletion: "2028-08-30",
  category: "Educational Infrastructure",
  subProjects: 2,
  daysRemaining: 1095,
  currentStage: "Project Submitted to AEE",
  lastUpdated: "8 August 2025",

  // Additional fields from PDF
  dateOfProposal: "2025-08-10",
  hasSubProjects: true,
  beneficiary: "Dhemaji",
  letterReference: "12980165",

  // Financial details
  fund: "Central Government Fund",
  function: "Infrastructure Development",
  budgetHead: "Revenue Expenditure",
  scheme: "Central Government Scheme",
  subScheme: "State Government Scheme",
  estimatedCost: 20000000,

  // Department information
  owningDepartment: "Education Department",
  executingDepartment: "Education Department",

  // Work details
  typeOfWork: "Construction",
  subTypeOfWork: "Building Construction",
  natureOfWork: "New Work",
  projectStartDate: "2025-08-15",
  projectEndDate: "2028-08-30",
  modeOfExecution: "Direct Assignment",

  // Location details
  district: "Dhemaji",
  block: "12",
  gramPanchayat: "122",
  latitude: 26.1619712,
  longitude: 91.7635072,

  documents: [
    {
      id: "1",
      name: "location_marker.png",
      type: "PNG",
      size: "0.05 MB",
      uploadedAt: "2025-08-07",
    },
    {
      id: "2",
      name: "location_marker.jpg",
      type: "JPG",
      size: "0.03 MB",
      uploadedAt: "2025-08-07",
    },
    {
      id: "3",
      name: "steps.jpg",
      type: "JPG",
      size: "0.01 MB",
      uploadedAt: "2025-08-07",
    },
  ],

  // Sub-projects from PDF
  subProjectDetails: [
    {
      id: "1",
      name: "Site Excavation",
      estimatedAmount: 1000000,
      typeOfWork: "Survey",
      subType: "Road Construction",
      nature: "New Work",
      startDate: "2025-10-01",
      endDate: "2025-12-31",
      status: "PENDING",
      progress: 0,
    },
    {
      id: "2",
      name: "New Link Road",
      estimatedAmount: 2000000,
      typeOfWork: "Construction",
      subType: "Road Construction",
      nature: "New Work",
      startDate: "2025-10-01",
      endDate: "2025-11-30",
      status: "PENDING",
      progress: 0,
    },
  ],
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "PROJ_1754574223988",
    name: "Engineering College Construction for Dhemaji",
    description:
      "This is a construction project of Engineering College, Dhemaji. This is a Central Government project.",
    status: "Submitted to AEE",
    progress: 15,
    budget: 20000000,
    budgetUtilized: 3000000,
    createdBy: "Ratan",
    createdByName: "Education Department",
    createdAt: "2025-08-06",
    updatedAt: "2025-08-07",
    startDate: "2025-08-15",
    expectedCompletion: "2028-08-30",
    category: "Educational Infrastructure",
    subProjects: 2,
    daysRemaining: 1095,
    currentStage: "Project Submitted to AEE",
    lastUpdated: "8 August 2025",
    dateOfProposal: "2025-08-10",
    hasSubProjects: true,
    beneficiary: "Dhemaji",
    letterReference: "12980165",
    fund: "Central Government Fund",
    function: "Infrastructure Development",
    budgetHead: "Revenue Expenditure",
    scheme: "Central Government Scheme",
    subScheme: "State Government Scheme",
    estimatedCost: 20000000,
    owningDepartment: "Education Department",
    executingDepartment: "Education Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Building Construction",
    natureOfWork: "New Work",
    projectStartDate: "2025-08-15",
    projectEndDate: "2028-08-30",
    modeOfExecution: "Direct Assignment",
    district: "Dhemaji",
    block: "12",
    gramPanchayat: "122",
    latitude: 26.1619712,
    longitude: 91.7635072,
    documents: [
      {
        id: "1",
        name: "location_marker.png",
        type: "PNG",
        size: "0.05 MB",
        uploadedAt: "2025-08-07",
      },
      {
        id: "2",
        name: "location_marker.jpg",
        type: "JPG",
        size: "0.03 MB",
        uploadedAt: "2025-08-07",
      },
      {
        id: "3",
        name: "steps.jpg",
        type: "JPG",
        size: "0.01 MB",
        uploadedAt: "2025-08-07",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Site Excavation",
        estimatedAmount: 1000000,
        typeOfWork: "Survey",
        subType: "Road Construction",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2025-12-31",
        status: "IN_PROGRESS",
        progress: 35,
      },
      {
        id: "2",
        name: "New Link Road",
        estimatedAmount: 2000000,
        typeOfWork: "Construction",
        subType: "Road Construction",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2025-11-30",
        status: "PENDING",
        progress: 0,
      },
    ],
  },

  {
    id: "PROJ_1754574223989",
    name: "District Hospital Modernization",
    description:
      "Comprehensive modernization and expansion of District Hospital in Guwahati with state-of-the-art medical facilities and equipment.",
    status: "Approved",
    progress: 67,
    budget: 15000000,
    budgetUtilized: 10050000,
    createdBy: "Priyam Sharma",
    createdByName: "Health Department",
    createdAt: "2024-12-15",
    updatedAt: "2025-08-06",
    startDate: "2025-01-10",
    expectedCompletion: "2026-12-31",
    category: "Healthcare Infrastructure",
    subProjects: 4,
    daysRemaining: 512,
    currentStage: "Under Construction - CE Approved",
    lastUpdated: "6 August 2025",
    dateOfProposal: "2024-12-15",
    hasSubProjects: true,
    beneficiary: "Guwahati Urban Area",
    letterReference: "12980166",
    fund: "State Government Fund",
    function: "Healthcare Development",
    budgetHead: "Capital Expenditure",
    scheme: "State Health Scheme",
    subScheme: "Hospital Modernization Program",
    estimatedCost: 15000000,
    owningDepartment: "Health Department",
    executingDepartment: "Health Department",
    typeOfWork: "Renovation",
    subTypeOfWork: "Hospital Infrastructure",
    natureOfWork: "Modernization",
    projectStartDate: "2025-01-10",
    projectEndDate: "2026-12-31",
    modeOfExecution: "Contractor",
    district: "Guwahati",
    block: "8",
    gramPanchayat: "101",
    latitude: 26.1445,
    longitude: 91.7362,
    documents: [
      {
        id: "1",
        name: "hospital_blueprint.pdf",
        type: "PDF",
        size: "2.1 MB",
        uploadedAt: "2024-12-15",
      },
      {
        id: "2",
        name: "equipment_list.xlsx",
        type: "XLSX",
        size: "0.8 MB",
        uploadedAt: "2025-01-05",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "OPD Block Construction",
        estimatedAmount: 5000000,
        typeOfWork: "Construction",
        subType: "Building Construction",
        nature: "New Work",
        startDate: "2025-01-10",
        endDate: "2025-08-15",
        status: "COMPLETED",
        progress: 100,
      },
      {
        id: "2",
        name: "ICU Equipment Installation",
        estimatedAmount: 4000000,
        typeOfWork: "Installation",
        subType: "Medical Equipment",
        nature: "New Work",
        startDate: "2025-06-01",
        endDate: "2025-10-30",
        status: "IN_PROGRESS",
        progress: 75,
      },
    ],
  },
];
