import { Project } from "@/types/projects.types";

export const PROJECT_STATUSES = {
  DRAFT: "Draft",
  SUBMITTED_TO_AEE: "Submitted to AEE",
  REJECTED_BY_AEE: "Rejected by AEE",
  SUBMITTED_TO_CE: "Submitted to CE",
  REJECTED_BY_CE: "Rejected by CE",
  SUBMITTED_TO_MD: "Submitted to MD",
  REJECTED_BY_MD: "Rejected by MD",
  SUBMITTED_TO_EXECUTING_DEPARTMENT: "Submitted to Executing Department",
  REJECTED_BY_EXECUTING_DEPARTMENT: "Rejected by Executing Department",
  APPROVED: "Approved",
  ONGOING: "Ongoing",
  PENDING: "Pending",
  COMPLETED: "Completed",
};

export const MOCK_PROJECT: Project = {
  id: "PROJ_1754574223988",
  name: "Engineering College Construction for Dhemaji",
  description:
    "This is a construction project of Engineering College, Dhemaji. This is a Central Government project.",
  status: "Submitted to AEE",
  progress: 0,
  budget: 20000000,
  budgetUtilized: 0,
  district: "Dhemaji",
  createdBy: "Ratan",
  createdByName: "Education Department",
  createdAt: "2025-08-10",
  updatedAt: "2025-08-07",
  startDate: "2025-08-15",
  expectedCompletion: "2028-08-30",
  category: "Educational Infrastructure",
  subProjects: 2,
  daysRemaining: 1095,
  currentStage: "Project Submitted to AEE",
  lastUpdated: "8 August 2025",

  // Additional fields from PDF
  dateOfProposal: "2025-08-10",
  hasSubProjects: true,
  beneficiary: "Dhemaji",
  letterReference: "12980165",

  // Financial details
  fund: "Central Government Fund",
  function: "Infrastructure Development",
  budgetHead: "Revenue Expenditure",
  scheme: "Central Government Scheme",
  subScheme: "State Government Scheme",
  estimatedCost: 20000000,

  // Department information
  owningDepartment: "Education Department",
  executingDepartment: "Education Department",

  // Work details
  typeOfWork: "Construction",
  subTypeOfWork: "Building Construction",
  natureOfWork: "New Work",
  projectStartDate: "2025-08-15",
  projectEndDate: "2028-08-30",
  modeOfExecution: "Direct Assignment",

  // Location details
  locality: "Dhemaji",
  ward: "12",
  ulb: "122",
  latitude: 26.1619712,
  longitude: 91.7635072,

  documents: [
    {
      id: "1",
      name: "location_marker.png",
      type: "PNG",
      size: "0.05 MB",
      uploadedAt: "2025-08-07",
    },
    {
      id: "2",
      name: "location_marker.jpg",
      type: "JPG",
      size: "0.03 MB",
      uploadedAt: "2025-08-07",
    },
    {
      id: "3",
      name: "steps.jpg",
      type: "JPG",
      size: "0.01 MB",
      uploadedAt: "2025-08-07",
    },
  ],

  // Sub-projects from PDF
  subProjectDetails: [
    {
      id: "1",
      name: "Site Excavation",
      estimatedAmount: 1000000,
      typeOfWork: "Survey",
      subType: "Road Construction",
      nature: "New Work",
      startDate: "2025-10-01",
      endDate: "2025-12-31",
      status: "PENDING",
      progress: 0,
    },
    {
      id: "2",
      name: "New Link Road",
      estimatedAmount: 2000000,
      typeOfWork: "Construction",
      subType: "Road Construction",
      nature: "New Work",
      startDate: "2025-10-01",
      endDate: "2025-11-30",
      status: "PENDING",
      progress: 0,
    },
  ],
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "PROJ_1754574223988",
    name: "Engineering College Construction for Dhemaji",
    description:
      "This is a construction project of Engineering College, Dhemaji. This is a Central Government project.",
    status: "Submitted to AEE",
    progress: 15,
    budget: 20000000,
    budgetUtilized: 3000000,
    district: "Dhemaji",
    createdBy: "Ratan",
    createdByName: "Education Department",
    createdAt: "2025-08-06",
    updatedAt: "2025-08-07",
    startDate: "2025-08-15",
    expectedCompletion: "2028-08-30",
    category: "Educational Infrastructure",
    subProjects: 2,
    daysRemaining: 1095,
    currentStage: "Project Submitted to AEE",
    lastUpdated: "8 August 2025",
    dateOfProposal: "2025-08-10",
    hasSubProjects: true,
    beneficiary: "Dhemaji",
    letterReference: "12980165",
    fund: "Central Government Fund",
    function: "Infrastructure Development",
    budgetHead: "Revenue Expenditure",
    scheme: "Central Government Scheme",
    subScheme: "State Government Scheme",
    estimatedCost: 20000000,
    owningDepartment: "Education Department",
    executingDepartment: "Education Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Building Construction",
    natureOfWork: "New Work",
    projectStartDate: "2025-08-15",
    projectEndDate: "2028-08-30",
    modeOfExecution: "Direct Assignment",
    locality: "Dhemaji",
    ward: "12",
    ulb: "122",
    latitude: 26.1619712,
    longitude: 91.7635072,
    documents: [
      {
        id: "1",
        name: "location_marker.png",
        type: "PNG",
        size: "0.05 MB",
        uploadedAt: "2025-08-07",
      },
      {
        id: "2",
        name: "location_marker.jpg",
        type: "JPG",
        size: "0.03 MB",
        uploadedAt: "2025-08-07",
      },
      {
        id: "3",
        name: "steps.jpg",
        type: "JPG",
        size: "0.01 MB",
        uploadedAt: "2025-08-07",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Site Excavation",
        estimatedAmount: 1000000,
        typeOfWork: "Survey",
        subType: "Road Construction",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2025-12-31",
        status: "IN_PROGRESS",
        progress: 35,
      },
      {
        id: "2",
        name: "New Link Road",
        estimatedAmount: 2000000,
        typeOfWork: "Construction",
        subType: "Road Construction",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2025-11-30",
        status: "PENDING",
        progress: 0,
      },
    ],
  },

  {
    id: "PROJ_1754574223989",
    name: "District Hospital Modernization",
    description:
      "Comprehensive modernization and expansion of District Hospital in Guwahati with state-of-the-art medical facilities and equipment.",
    status: "Approved",
    progress: 67,
    budget: 15000000,
    budgetUtilized: 10050000,
    district: "Guwahati",
    createdBy: "Dr. Priya Sharma",
    createdByName: "Health Department",
    createdAt: "2024-12-15",
    updatedAt: "2025-08-06",
    startDate: "2025-01-10",
    expectedCompletion: "2026-12-31",
    category: "Healthcare Infrastructure",
    subProjects: 4,
    daysRemaining: 512,
    currentStage: "Under Construction - CE Approved",
    lastUpdated: "6 August 2025",
    dateOfProposal: "2024-12-15",
    hasSubProjects: true,
    beneficiary: "Guwahati Urban Area",
    letterReference: "12980166",
    fund: "State Government Fund",
    function: "Healthcare Development",
    budgetHead: "Capital Expenditure",
    scheme: "State Health Scheme",
    subScheme: "Hospital Modernization Program",
    estimatedCost: 15000000,
    owningDepartment: "Health Department",
    executingDepartment: "Health Department",
    typeOfWork: "Renovation",
    subTypeOfWork: "Hospital Infrastructure",
    natureOfWork: "Modernization",
    projectStartDate: "2025-01-10",
    projectEndDate: "2026-12-31",
    modeOfExecution: "Contractor",
    locality: "Guwahati",
    ward: "8",
    ulb: "101",
    latitude: 26.1445,
    longitude: 91.7362,
    documents: [
      {
        id: "1",
        name: "hospital_blueprint.pdf",
        type: "PDF",
        size: "2.1 MB",
        uploadedAt: "2024-12-15",
      },
      {
        id: "2",
        name: "equipment_list.xlsx",
        type: "XLSX",
        size: "0.8 MB",
        uploadedAt: "2025-01-05",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "OPD Block Construction",
        estimatedAmount: 5000000,
        typeOfWork: "Construction",
        subType: "Building Construction",
        nature: "New Work",
        startDate: "2025-01-10",
        endDate: "2025-08-15",
        status: "COMPLETED",
        progress: 100,
      },
      {
        id: "2",
        name: "ICU Equipment Installation",
        estimatedAmount: 4000000,
        typeOfWork: "Installation",
        subType: "Medical Equipment",
        nature: "New Work",
        startDate: "2025-06-01",
        endDate: "2025-10-30",
        status: "IN_PROGRESS",
        progress: 75,
      },
    ],
  },

  {
    id: "PROJ_1754574223990",
    name: "Smart City Road Network",
    description:
      "Development of smart road infrastructure with LED lighting, traffic management systems, and pedestrian facilities in Silchar city center.",
    status: "Ongoing",
    progress: 42,
    budget: 8500000,
    budgetUtilized: 3570000,
    district: "Silchar",
    createdBy: "Rajesh Kumar",
    createdByName: "Urban Development Department",
    createdAt: "2024-10-20",
    updatedAt: "2025-08-08",
    startDate: "2025-03-01",
    expectedCompletion: "2026-06-30",
    category: "Urban Infrastructure",
    subProjects: 3,
    daysRemaining: 691,
    currentStage: "Construction Phase - 42% Complete",
    lastUpdated: "8 August 2025",
    dateOfProposal: "2024-10-20",
    hasSubProjects: true,
    beneficiary: "Silchar Municipality",
    letterReference: "12980167",
    fund: "Central Government Fund",
    function: "Urban Development",
    budgetHead: "Capital Expenditure",
    scheme: "Smart Cities Mission",
    subScheme: "Infrastructure Development",
    estimatedCost: 8500000,
    owningDepartment: "Urban Development Department",
    executingDepartment: "Public Works Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Road Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2025-03-01",
    projectEndDate: "2026-06-30",
    modeOfExecution: "Tender",
    locality: "Silchar",
    ward: "15",
    ulb: "145",
    latitude: 24.8333,
    longitude: 92.7789,
    documents: [
      {
        id: "1",
        name: "road_design.dwg",
        type: "DWG",
        size: "5.2 MB",
        uploadedAt: "2024-10-20",
      },
      {
        id: "2",
        name: "traffic_study.pdf",
        type: "PDF",
        size: "1.5 MB",
        uploadedAt: "2024-11-15",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Main Road Construction",
        estimatedAmount: 4500000,
        typeOfWork: "Construction",
        subType: "Road Construction",
        nature: "New Work",
        startDate: "2025-03-01",
        endDate: "2025-12-31",
        status: "IN_PROGRESS",
        progress: 58,
      },
      {
        id: "2",
        name: "LED Street Lighting",
        estimatedAmount: 2000000,
        typeOfWork: "Installation",
        subType: "Electrical Works",
        nature: "New Work",
        startDate: "2025-08-01",
        endDate: "2026-02-28",
        status: "IN_PROGRESS",
        progress: 25,
      },
    ],
  },

  {
    id: "PROJ_1754574223991",
    name: "Rural Water Supply Scheme",
    description:
      "Implementation of comprehensive rural water supply system covering 45 villages in Dibrugarh district with pipeline network and water treatment facilities.",
    status: "Pending",
    progress: 0,
    budget: 12000000,
    budgetUtilized: 0,
    district: "Dibrugarh",
    createdBy: "Anita Das",
    createdByName: "Rural Development Department",
    createdAt: "2025-07-25",
    updatedAt: "2025-08-05",
    startDate: "2025-10-01",
    expectedCompletion: "2027-03-31",
    category: "Water Supply",
    subProjects: 5,
    daysRemaining: 0,
    currentStage: "Pending Approval from MD",
    lastUpdated: "5 August 2025",
    dateOfProposal: "2025-07-25",
    hasSubProjects: true,
    beneficiary: "45 Villages in Dibrugarh",
    letterReference: "12980168",
    fund: "Central Government Fund",
    function: "Rural Development",
    budgetHead: "Capital Expenditure",
    scheme: "Jal Jeevan Mission",
    subScheme: "Rural Water Supply",
    estimatedCost: 12000000,
    owningDepartment: "Rural Development Department",
    executingDepartment: "Water Resources Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Water Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2025-10-01",
    projectEndDate: "2027-03-31",
    modeOfExecution: "Direct Assignment",
    locality: "Dibrugarh Rural",
    ward: "Multiple",
    ulb: "201",
    latitude: 27.4728,
    longitude: 94.912,
    documents: [
      {
        id: "1",
        name: "village_survey.pdf",
        type: "PDF",
        size: "3.2 MB",
        uploadedAt: "2025-07-25",
      },
      {
        id: "2",
        name: "water_quality_report.pdf",
        type: "PDF",
        size: "1.1 MB",
        uploadedAt: "2025-08-01",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Water Treatment Plant",
        estimatedAmount: 4000000,
        typeOfWork: "Construction",
        subType: "Water Treatment",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2026-06-30",
        status: "PENDING",
        progress: 0,
      },
      {
        id: "2",
        name: "Pipeline Network",
        estimatedAmount: 6000000,
        typeOfWork: "Installation",
        subType: "Pipeline Works",
        nature: "New Work",
        startDate: "2026-01-01",
        endDate: "2027-01-31",
        status: "PENDING",
        progress: 0,
      },
    ],
  },

  {
    id: "PROJ_1754574223992",
    name: "Skill Development Center",
    description:
      "Establishment of modern skill development center with training facilities for technical and vocational education in Jorhat district.",
    status: "Completed",
    progress: 100,
    budget: 6000000,
    budgetUtilized: 5850000,
    district: "Jorhat",
    createdBy: "Vikram Singh",
    createdByName: "Skill Development Department",
    createdAt: "2023-05-10",
    updatedAt: "2025-03-15",
    startDate: "2023-08-01",
    expectedCompletion: "2025-02-28",
    category: "Educational Infrastructure",
    subProjects: 2,
    daysRemaining: 0,
    currentStage: "Project Completed Successfully",
    lastUpdated: "15 March 2025",
    dateOfProposal: "2023-05-10",
    hasSubProjects: true,
    beneficiary: "Jorhat District Youth",
    letterReference: "12980169",
    fund: "State Government Fund",
    function: "Skill Development",
    budgetHead: "Revenue Expenditure",
    scheme: "State Skill Development Scheme",
    subScheme: "Technical Training Centers",
    estimatedCost: 6000000,
    owningDepartment: "Skill Development Department",
    executingDepartment: "Education Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Educational Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2023-08-01",
    projectEndDate: "2025-02-28",
    modeOfExecution: "Contractor",
    locality: "Jorhat",
    ward: "7",
    ulb: "156",
    latitude: 26.7509,
    longitude: 94.2037,
    documents: [
      {
        id: "1",
        name: "completion_certificate.pdf",
        type: "PDF",
        size: "0.9 MB",
        uploadedAt: "2025-03-15",
      },
      {
        id: "2",
        name: "final_inspection.pdf",
        type: "PDF",
        size: "1.2 MB",
        uploadedAt: "2025-03-10",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Training Hall Construction",
        estimatedAmount: 3500000,
        typeOfWork: "Construction",
        subType: "Building Construction",
        nature: "New Work",
        startDate: "2023-08-01",
        endDate: "2024-06-30",
        status: "COMPLETED",
        progress: 100,
      },
      {
        id: "2",
        name: "Equipment Installation",
        estimatedAmount: 2500000,
        typeOfWork: "Installation",
        subType: "Training Equipment",
        nature: "New Work",
        startDate: "2024-07-01",
        endDate: "2025-02-28",
        status: "COMPLETED",
        progress: 100,
      },
    ],
  },

  {
    id: "PROJ_1754574223993",
    name: "Solar Power Grid",
    description:
      "Installation of 5MW solar power generation facility with grid connectivity to support renewable energy initiatives in Tezpur region.",
    status: "Pending",
    progress: 5,
    budget: 25000000,
    budgetUtilized: 1250000,
    district: "Tezpur",
    createdBy: "Meera Patel",
    createdByName: "Energy Department",
    createdAt: "2024-11-30",
    updatedAt: "2025-06-20",
    startDate: "2025-04-01",
    expectedCompletion: "2026-11-30",
    category: "Renewable Energy",
    subProjects: 3,
    daysRemaining: 0,
    currentStage: "Project Rejected - Technical Issues",
    lastUpdated: "20 June 2025",
    dateOfProposal: "2024-11-30",
    hasSubProjects: true,
    beneficiary: "Tezpur Regional Grid",
    letterReference: "12980170",
    fund: "Central Government Fund",
    function: "Energy Development",
    budgetHead: "Capital Expenditure",
    scheme: "National Solar Mission",
    subScheme: "Grid Connected Solar",
    estimatedCost: 25000000,
    owningDepartment: "Energy Department",
    executingDepartment: "Power Department",
    typeOfWork: "Installation",
    subTypeOfWork: "Solar Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2025-04-01",
    projectEndDate: "2026-11-30",
    modeOfExecution: "Tender",
    locality: "Tezpur",
    ward: "11",
    ulb: "178",
    latitude: 26.634,
    longitude: 92.7965,
    documents: [
      {
        id: "1",
        name: "technical_feasibility.pdf",
        type: "PDF",
        size: "4.5 MB",
        uploadedAt: "2024-11-30",
      },
      {
        id: "2",
        name: "rejection_notice.pdf",
        type: "PDF",
        size: "0.3 MB",
        uploadedAt: "2025-06-20",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Land Preparation",
        estimatedAmount: 2000000,
        typeOfWork: "Preparation",
        subType: "Site Development",
        nature: "New Work",
        startDate: "2025-04-01",
        endDate: "2025-06-30",
        status: "REJECTED",
        progress: 15,
      },
      {
        id: "2",
        name: "Solar Panel Installation",
        estimatedAmount: 18000000,
        typeOfWork: "Installation",
        subType: "Solar Equipment",
        nature: "New Work",
        startDate: "2025-07-01",
        endDate: "2026-06-30",
        status: "REJECTED",
        progress: 0,
      },
    ],
  },

  {
    id: "PROJ_1754574223994",
    name: "Community Health Center",
    description:
      "Construction of new Community Health Center with modern medical facilities, ambulance services, and telemedicine capabilities in Bongaigaon.",
    status: "Approved",
    progress: 28,
    budget: 9500000,
    budgetUtilized: 2660000,
    district: "Bongaigaon",
    createdBy: "Dr. Kavita Reddy",
    createdByName: "Health Department",
    createdAt: "2024-09-15",
    updatedAt: "2025-08-07",
    startDate: "2025-02-01",
    expectedCompletion: "2026-08-31",
    category: "Healthcare Infrastructure",
    subProjects: 3,
    daysRemaining: 754,
    currentStage: "MD Approved - Under Construction",
    lastUpdated: "7 August 2025",
    dateOfProposal: "2024-09-15",
    hasSubProjects: true,
    beneficiary: "Bongaigaon District",
    letterReference: "12980171",
    fund: "State Government Fund",
    function: "Healthcare Development",
    budgetHead: "Capital Expenditure",
    scheme: "Rural Health Mission",
    subScheme: "Community Health Centers",
    estimatedCost: 9500000,
    owningDepartment: "Health Department",
    executingDepartment: "Health Department",
    typeOfWork: "Construction",
    subTypeOfWork: "Healthcare Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2025-02-01",
    projectEndDate: "2026-08-31",
    modeOfExecution: "Direct Assignment",
    locality: "Bongaigaon",
    ward: "5",
    ulb: "133",
    latitude: 26.4831,
    longitude: 90.55,
    documents: [
      {
        id: "1",
        name: "medical_layout.pdf",
        type: "PDF",
        size: "2.8 MB",
        uploadedAt: "2024-09-15",
      },
      {
        id: "2",
        name: "progress_report.xlsx",
        type: "XLSX",
        size: "0.6 MB",
        uploadedAt: "2025-08-07",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Main Building Construction",
        estimatedAmount: 6500000,
        typeOfWork: "Construction",
        subType: "Building Construction",
        nature: "New Work",
        startDate: "2025-02-01",
        endDate: "2026-01-31",
        status: "IN_PROGRESS",
        progress: 35,
      },
      {
        id: "2",
        name: "Medical Equipment Procurement",
        estimatedAmount: 3000000,
        typeOfWork: "Procurement",
        subType: "Medical Equipment",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2026-06-30",
        status: "PENDING",
        progress: 0,
      },
    ],
  },

  {
    id: "PROJ_1754574223995",
    name: "Digital Library Network",
    description:
      "Establishment of digital library network connecting 20 schools and colleges in Nagaon district with high-speed internet and digital resources.",
    status: "Submitted to AEE",
    progress: 8,
    budget: 4500000,
    budgetUtilized: 360000,
    district: "Nagaon",
    createdBy: "Amit Sharma",
    createdByName: "Education Department",
    createdAt: "2025-06-01",
    updatedAt: "2025-08-08",
    startDate: "2025-09-01",
    expectedCompletion: "2026-12-31",
    category: "Digital Infrastructure",
    subProjects: 4,
    daysRemaining: 873,
    currentStage: "Submitted to CE for Review",
    lastUpdated: "8 August 2025",
    dateOfProposal: "2025-06-01",
    hasSubProjects: true,
    beneficiary: "20 Educational Institutions",
    letterReference: "12980172",
    fund: "Central Government Fund",
    function: "Digital Education",
    budgetHead: "Revenue Expenditure",
    scheme: "Digital India Initiative",
    subScheme: "Educational Technology",
    estimatedCost: 4500000,
    owningDepartment: "Education Department",
    executingDepartment: "IT Department",
    typeOfWork: "Installation",
    subTypeOfWork: "IT Infrastructure",
    natureOfWork: "New Work",
    projectStartDate: "2025-09-01",
    projectEndDate: "2026-12-31",
    modeOfExecution: "Tender",
    locality: "Nagaon",
    ward: "Multiple",
    ulb: "167",
    latitude: 26.3479,
    longitude: 92.6831,
    documents: [
      {
        id: "1",
        name: "network_topology.pdf",
        type: "PDF",
        size: "1.8 MB",
        uploadedAt: "2025-06-01",
      },
      {
        id: "2",
        name: "school_list.xlsx",
        type: "XLSX",
        size: "0.4 MB",
        uploadedAt: "2025-06-15",
      },
    ],
    subProjectDetails: [
      {
        id: "1",
        name: "Network Infrastructure Setup",
        estimatedAmount: 2000000,
        typeOfWork: "Installation",
        subType: "Network Equipment",
        nature: "New Work",
        startDate: "2025-09-01",
        endDate: "2026-03-31",
        status: "PENDING",
        progress: 0,
      },
      {
        id: "2",
        name: "Digital Content Development",
        estimatedAmount: 1500000,
        typeOfWork: "Development",
        subType: "Software Development",
        nature: "New Work",
        startDate: "2025-10-01",
        endDate: "2026-08-31",
        status: "PENDING",
        progress: 0,
      },
    ],
  },
];
